package project_peter_client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class RoomGame extends javax.swing.JFrame {

    Socket socket;
    BufferedReader input;
    PrintStream output;
    String username;
    int idLobby;
    Music lagu = new Music();

    public void setIdLobby(int idLobby) {
        this.idLobby = idLobby;
    }
    public RoomGame() {
        initComponents();
        this.getRootPane().setDefaultButton(btnSendPesan);
    }

    public void setSocket(Socket socket) {
        this.socket = socket;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPlayer1 = new javax.swing.JTextField();
        txtPlayer2 = new javax.swing.JTextField();
        txtPlayer3 = new javax.swing.JTextField();
        txtPlayer4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarChatRoom = new javax.swing.JTextArea();
        txtPesan = new javax.swing.JTextField();
        btnSendPesan = new javax.swing.JButton();
        btnExitRoom = new javax.swing.JButton();
        btnReady = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Game of Brain");
        setLocation(new java.awt.Point(50, 50));
        setPreferredSize(new java.awt.Dimension(901, 601));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        txtPlayer1.setEditable(false);
        txtPlayer1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPlayer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtPlayer1);
        txtPlayer1.setBounds(270, 180, 120, 35);

        txtPlayer2.setEditable(false);
        txtPlayer2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPlayer2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtPlayer2);
        txtPlayer2.setBounds(540, 180, 120, 35);

        txtPlayer3.setEditable(false);
        txtPlayer3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPlayer3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtPlayer3);
        txtPlayer3.setBounds(270, 260, 120, 35);

        txtPlayer4.setEditable(false);
        txtPlayer4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPlayer4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtPlayer4);
        txtPlayer4.setBounds(540, 260, 120, 35);

        tarChatRoom.setEditable(false);
        tarChatRoom.setColumns(20);
        tarChatRoom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tarChatRoom.setRows(5);
        jScrollPane1.setViewportView(tarChatRoom);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 320, 510, 130);
        getContentPane().add(txtPesan);
        txtPesan.setBounds(210, 460, 390, 30);

        btnSendPesan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSendPesan.setText("Kirim");
        btnSendPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPesanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSendPesan);
        btnSendPesan.setBounds(610, 460, 110, 30);

        btnExitRoom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExitRoom.setText("Keluar Room");
        btnExitRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnExitRoom);
        btnExitRoom.setBounds(610, 510, 110, 30);

        btnReady.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReady.setText("Ready");
        btnReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadyActionPerformed(evt);
            }
        });
        getContentPane().add(btnReady);
        btnReady.setBounds(490, 510, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profil_48.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(670, 170, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profil_48.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 170, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profil_48.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 250, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profil_48.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(670, 250, 50, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            lagu.room();
            input = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            output= new PrintStream(socket.getOutputStream());
            output.println("/ambilNamaDariLobby "+idLobby);
             new Thread(new Runnable(){
                @Override
                public void run() {
                    while(true){
                        try {
                            Thread.sleep(100);
                            String message = input.readLine();
                            if(message.startsWith("/namaPlayerDariLobby;")){
                                String nama = message.split(";")[1];
                                if(txtPlayer1.getText().isEmpty()||txtPlayer1.getText().equalsIgnoreCase(nama)){
                                    txtPlayer1.setText(nama);
                                    txtPlayer2.setText("");
                                    txtPlayer3.setText("");
                                    txtPlayer4.setText("");
                                }
                                else if(txtPlayer2.getText().isEmpty()||txtPlayer2.getText().equalsIgnoreCase(nama)){
                                    txtPlayer2.setText(nama);
                                }
                                else if(txtPlayer3.getText().isEmpty()||txtPlayer3.getText().equalsIgnoreCase(nama)){
                                    txtPlayer3.setText(nama);
                                }
                                else if(txtPlayer4.getText().isEmpty()||txtPlayer4.getText().equalsIgnoreCase(nama)){
                                    txtPlayer4.setText(nama);
                                }
                            }
                            else if(message.startsWith("/quitAccept"))
                            {
                                MenuUtama menu = new MenuUtama();
                                menu.setSocket(socket);
                                menu.setUsername(username);
                                menu.setVisible(true);
                                close();
                                break;
                            }
                            else if(message.startsWith("/lobbyChatAccept;"))
                            {
                                String pesan = message.split(";")[1];
                                tarChatRoom.append(pesan+"\n");
                            }
                            else if(message.startsWith("/cautionGameStarted;"))
                            {
                                String pesan = message.split(";")[1];
                                tarChatRoom.setText(pesan);
                            }
                            else if(message.startsWith("/play")){
                                PlayMenu play = new PlayMenu();
                                play.setUsername(username);
                                play.setSocket(socket);
                                play.setIdLobby(idLobby);
                                play.setVisible(true);
                                close();
                                break;
                            }
                            else if(message.startsWith("/can'tPlay"))
                            {
                                JOptionPane.showMessageDialog(null, "Tunggu pemain lain..");
                            }
                            if(tarChatRoom.getText().equalsIgnoreCase("Game_Start()")){
                                PlayMenu play = new PlayMenu();
                                play.setUsername(username);
                                play.setSocket(socket);
                                play.setIdLobby(idLobby);
                                play.setVisible(true);
                                close();
                                break;
                            }
                        } catch (InterruptedException | IOException ex) {
                            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }).start();

        } catch (IOException ex) {
            Logger.getLogger(RoomGame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowOpened
    private void close()
    {
        lagu.stop();
        this.dispose();
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        lagu.stop();
//        try {
//            output = new PrintStream(socket.getOutputStream());
//            output.println("/quitLobby "+idLobby);
//            output.println("/keluar");
//        } catch (IOException ex) {
//            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_formWindowClosing

    private void btnExitRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitRoomActionPerformed
        try {
            output = new PrintStream(socket.getOutputStream());
            output.println("/quitLobby "+idLobby);
        } catch (IOException ex) {
            Logger.getLogger(RoomGame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnExitRoomActionPerformed

    private void btnSendPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPesanActionPerformed
        try {
            output = new PrintStream(socket.getOutputStream());
            output.println("/lobbyChat;"+txtPesan.getText());
            tarChatRoom.append("saya : "+txtPesan.getText()+"\n");
            txtPesan.setText("");
        } catch (IOException ex) {
            Logger.getLogger(RoomGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSendPesanActionPerformed

    private void btnReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadyActionPerformed
        try {
            output = new PrintStream(socket.getOutputStream());
            output.println("/playReady "+idLobby);
        } catch (IOException ex) {
            Logger.getLogger(RoomGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReadyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnExitRoom;
    private javax.swing.JButton btnReady;
    private javax.swing.JButton btnSendPesan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tarChatRoom;
    private javax.swing.JTextField txtPesan;
    private javax.swing.JTextField txtPlayer1;
    private javax.swing.JTextField txtPlayer2;
    private javax.swing.JTextField txtPlayer3;
    private javax.swing.JTextField txtPlayer4;
    // End of variables declaration//GEN-END:variables
}
