/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_peter_client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author Asus
 */
public class TambahSoal extends javax.swing.JFrame {

    Socket socket;
    BufferedReader input;
    PrintStream output;
    private String username;
    public TambahSoal() {
        initComponents();
        groupRadioButton();
    }
    private void groupRadioButton(){
        buttonGroup1.add(rdoA);
        buttonGroup1.add(rdoB);
        buttonGroup1.add(rdoC);
        buttonGroup1.add(rdoD);
    }

    public void setSocket(Socket socket) {
        this.socket = socket;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarSoal = new javax.swing.JTextArea();
        rdoA = new javax.swing.JRadioButton();
        rdoB = new javax.swing.JRadioButton();
        rdoC = new javax.swing.JRadioButton();
        rdoD = new javax.swing.JRadioButton();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        txtD = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tambah Soal");
        setLocation(new java.awt.Point(50, 50));
        setPreferredSize(new java.awt.Dimension(905, 625));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tarSoal.setColumns(20);
        tarSoal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tarSoal.setRows(5);
        jScrollPane2.setViewportView(tarSoal);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(220, 160, 490, 150);

        rdoA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoA.setText("A :");
        rdoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAActionPerformed(evt);
            }
        });
        getContentPane().add(rdoA);
        rdoA.setBounds(220, 330, 50, 30);

        rdoB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoB.setText("B :");
        getContentPane().add(rdoB);
        rdoB.setBounds(220, 370, 50, 30);

        rdoC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoC.setText("C :");
        getContentPane().add(rdoC);
        rdoC.setBounds(220, 410, 50, 30);

        rdoD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoD.setText("D :");
        getContentPane().add(rdoD);
        rdoD.setBounds(220, 450, 50, 30);

        txtA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtA.setText(" ");
        getContentPane().add(txtA);
        txtA.setBounds(280, 330, 430, 30);

        txtB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtB.setText(" ");
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        getContentPane().add(txtB);
        txtB.setBounds(280, 370, 430, 30);

        txtC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtC.setText(" ");
        getContentPane().add(txtC);
        txtC.setBounds(280, 410, 430, 30);

        txtD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtD.setText(" ");
        getContentPane().add(txtD);
        txtD.setBounds(280, 450, 430, 30);

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah);
        btnTambah.setBounds(610, 490, 100, 30);

        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali);
        btnKembali.setBounds(500, 490, 100, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            input = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            output = new PrintStream(socket.getOutputStream());
            new Thread(new Runnable(){
                @Override
                public void run() {
                    while(true){
                        try {
                            Thread.sleep(100);
                            String message = input.readLine();
                            if(message.startsWith("/accept")){
                                MenuUtama menu = new MenuUtama();
                                menu.setUsername(username);
                                menu.setSocket(socket);
                                menu.setVisible(true);
                                close();
                                break;
                            }
                            else if(message.startsWith("/soalBaruTerbuat")){
                                JOptionPane.showMessageDialog(null, "Soal berhasil dibuat");
                            }
                            else if(message.startsWith("/soalBaruGagalTerbuat")){
                                JOptionPane.showMessageDialog(null, "Gagal membuat soal");
                            }
                        } catch (InterruptedException | IOException ex) {
                            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }).start();
        } catch (IOException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        try {
            output = new PrintStream(socket.getOutputStream());
            output.println("/kembaliMenuUtama");
        } catch (IOException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        boolean kondisi =true;
        String jawaban="";
        String a="";
        String b="";
        String c="";
        String d="";
        String soal="";
        
        String error="";
        if(!tarSoal.getText().trim().isEmpty())
            soal = tarSoal.getText();
        else{
            kondisi=false;
            error+="Isi dulu soalnya\n";
        }
        if(!txtA.getText().trim().isEmpty())
            a=txtA.getText();
        else {
            kondisi=false;
            error+="Isi dulu textfield A\n";
        }
        if(!txtB.getText().trim().isEmpty())
            b=txtB.getText();
        else {
            kondisi=false;
            error+= "Isi dulu textfield B\n";
        }
        if(!txtC.getText().trim().isEmpty())
            c=txtC.getText();
        else {
            kondisi=false;
            error+="Isi dulu textfield C\n";
        }
        if(!txtD.getText().trim().isEmpty())
            d=txtD.getText();
        else {
            kondisi=false;
            error+= "Isi dulu textfield D\n";
        }
        
        
        if(rdoA.isSelected())
            jawaban="A";
        else if(rdoB.isSelected())
            jawaban="B";
        else if(rdoC.isSelected())
            jawaban="C";
        else if(rdoD.isSelected())
            jawaban="D";
        else{
            kondisi=false;
            error+="Pilih jawaban benar\n";
        }
        if(kondisi){
            try {
                output = new PrintStream(socket.getOutputStream());
                output.println("/simpanSoalBaru;"+soal+";"+a+";"+b+";"+c+";"+d+";"+jawaban);
            } catch (IOException ex) {
                Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(null, error);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void rdoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoAActionPerformed
    private void close(){
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahSoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahSoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahSoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahSoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahSoal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoA;
    private javax.swing.JRadioButton rdoB;
    private javax.swing.JRadioButton rdoC;
    private javax.swing.JRadioButton rdoD;
    private javax.swing.JTextArea tarSoal;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtD;
    // End of variables declaration//GEN-END:variables
}
